// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example-service.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExampleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleRequest) Reset()         { *m = ExampleRequest{} }
func (m *ExampleRequest) String() string { return proto.CompactTextString(m) }
func (*ExampleRequest) ProtoMessage()    {}
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65acb1d76e546e2, []int{0}
}

func (m *ExampleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleRequest.Unmarshal(m, b)
}
func (m *ExampleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleRequest.Marshal(b, m, deterministic)
}
func (m *ExampleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleRequest.Merge(m, src)
}
func (m *ExampleRequest) XXX_Size() int {
	return xxx_messageInfo_ExampleRequest.Size(m)
}
func (m *ExampleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleRequest proto.InternalMessageInfo

type ExampleResponse struct {
	Slice                []*Outer `protobuf:"bytes,1,rep,name=slice,proto3" json:"slice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleResponse) Reset()         { *m = ExampleResponse{} }
func (m *ExampleResponse) String() string { return proto.CompactTextString(m) }
func (*ExampleResponse) ProtoMessage()    {}
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65acb1d76e546e2, []int{1}
}

func (m *ExampleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleResponse.Unmarshal(m, b)
}
func (m *ExampleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleResponse.Marshal(b, m, deterministic)
}
func (m *ExampleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleResponse.Merge(m, src)
}
func (m *ExampleResponse) XXX_Size() int {
	return xxx_messageInfo_ExampleResponse.Size(m)
}
func (m *ExampleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleResponse proto.InternalMessageInfo

func (m *ExampleResponse) GetSlice() []*Outer {
	if m != nil {
		return m.Slice
	}
	return nil
}

type Outer struct {
	Col1                 string   `protobuf:"bytes,1,opt,name=col1,proto3" json:"col1,omitempty"`
	Col2                 int64    `protobuf:"varint,2,opt,name=col2,proto3" json:"col2,omitempty"`
	Inner                *Inner   `protobuf:"bytes,3,opt,name=inner,proto3" json:"inner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer) Reset()         { *m = Outer{} }
func (m *Outer) String() string { return proto.CompactTextString(m) }
func (*Outer) ProtoMessage()    {}
func (*Outer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65acb1d76e546e2, []int{2}
}

func (m *Outer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer.Unmarshal(m, b)
}
func (m *Outer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer.Marshal(b, m, deterministic)
}
func (m *Outer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer.Merge(m, src)
}
func (m *Outer) XXX_Size() int {
	return xxx_messageInfo_Outer.Size(m)
}
func (m *Outer) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer.DiscardUnknown(m)
}

var xxx_messageInfo_Outer proto.InternalMessageInfo

func (m *Outer) GetCol1() string {
	if m != nil {
		return m.Col1
	}
	return ""
}

func (m *Outer) GetCol2() int64 {
	if m != nil {
		return m.Col2
	}
	return 0
}

func (m *Outer) GetInner() *Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

type Inner struct {
	Col3                 bool              `protobuf:"varint,1,opt,name=col3,proto3" json:"col3,omitempty"`
	Col4                 []string          `protobuf:"bytes,2,rep,name=col4,proto3" json:"col4,omitempty"`
	Col5                 map[string]string `protobuf:"bytes,3,rep,name=col5,proto3" json:"col5,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Inner) Reset()         { *m = Inner{} }
func (m *Inner) String() string { return proto.CompactTextString(m) }
func (*Inner) ProtoMessage()    {}
func (*Inner) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65acb1d76e546e2, []int{3}
}

func (m *Inner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inner.Unmarshal(m, b)
}
func (m *Inner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inner.Marshal(b, m, deterministic)
}
func (m *Inner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inner.Merge(m, src)
}
func (m *Inner) XXX_Size() int {
	return xxx_messageInfo_Inner.Size(m)
}
func (m *Inner) XXX_DiscardUnknown() {
	xxx_messageInfo_Inner.DiscardUnknown(m)
}

var xxx_messageInfo_Inner proto.InternalMessageInfo

func (m *Inner) GetCol3() bool {
	if m != nil {
		return m.Col3
	}
	return false
}

func (m *Inner) GetCol4() []string {
	if m != nil {
		return m.Col4
	}
	return nil
}

func (m *Inner) GetCol5() map[string]string {
	if m != nil {
		return m.Col5
	}
	return nil
}

func init() {
	proto.RegisterType((*ExampleRequest)(nil), "main.ExampleRequest")
	proto.RegisterType((*ExampleResponse)(nil), "main.ExampleResponse")
	proto.RegisterType((*Outer)(nil), "main.Outer")
	proto.RegisterType((*Inner)(nil), "main.Inner")
	proto.RegisterMapType((map[string]string)(nil), "main.Inner.Col5Entry")
}

func init() {
	proto.RegisterFile("example-service.proto", fileDescriptor_f65acb1d76e546e2)
}

var fileDescriptor_f65acb1d76e546e2 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0xc9, 0x6e, 0x57, 0x6d, 0x8a, 0x5a, 0x62, 0x0b, 0xa1, 0x78, 0x58, 0xf7, 0x54, 0x0f,
	0xee, 0xd2, 0x6d, 0x8b, 0xe2, 0x55, 0x7a, 0x10, 0x0f, 0x42, 0x3c, 0x7b, 0x88, 0x65, 0x28, 0xc1,
	0x34, 0x59, 0x37, 0x69, 0xb1, 0x57, 0x5f, 0xa1, 0x8f, 0xe6, 0x2b, 0xf8, 0x20, 0xb2, 0x49, 0x58,
	0xff, 0xdc, 0x92, 0x2f, 0x93, 0x6f, 0x86, 0xdf, 0xe0, 0x21, 0xbc, 0xf3, 0x75, 0x25, 0xe1, 0xca,
	0x40, 0xbd, 0x15, 0x4b, 0xc8, 0xab, 0x5a, 0x5b, 0x4d, 0x3a, 0x6b, 0x2e, 0xd4, 0xe8, 0x7c, 0xa5,
	0xf5, 0x4a, 0x42, 0xc1, 0x2b, 0x51, 0x70, 0xa5, 0xb4, 0xe5, 0x56, 0x68, 0x65, 0x7c, 0x4d, 0xd6,
	0xc7, 0x27, 0x0b, 0xff, 0x99, 0xc1, 0xdb, 0x06, 0x8c, 0xcd, 0x66, 0xf8, 0xb4, 0x25, 0xa6, 0xd2,
	0xca, 0x00, 0xb9, 0xc0, 0x89, 0x91, 0x62, 0x09, 0x14, 0xa5, 0xf1, 0xb8, 0x57, 0xf6, 0xf2, 0x46,
	0x9c, 0x3f, 0x6e, 0x2c, 0xd4, 0xcc, 0xbf, 0x64, 0x0c, 0x27, 0xee, 0x4e, 0x08, 0xee, 0x2c, 0xb5,
	0x9c, 0x50, 0x94, 0xa2, 0x71, 0x97, 0xb9, 0x73, 0x60, 0x25, 0x8d, 0x52, 0x34, 0x8e, 0x1d, 0x2b,
	0x1b, 0xa7, 0x50, 0x0a, 0x6a, 0x1a, 0xa7, 0xe8, 0xc7, 0x79, 0xdf, 0x20, 0xe6, 0x5f, 0xb2, 0x3d,
	0xc2, 0x89, 0x03, 0x41, 0x30, 0x75, 0xd2, 0x23, 0x27, 0x98, 0x06, 0x36, 0xa3, 0x51, 0x1a, 0x87,
	0x46, 0x33, 0x72, 0xe9, 0xd8, 0x9c, 0xc6, 0x6e, 0xce, 0xe1, 0x2f, 0x67, 0x7e, 0xa7, 0xe5, 0x7c,
	0xa1, 0x6c, 0xbd, 0x73, 0xa5, 0xf3, 0xd1, 0x35, 0xee, 0xb6, 0x88, 0xf4, 0x71, 0xfc, 0x0a, 0xbb,
	0x30, 0x73, 0x73, 0x24, 0x03, 0x9c, 0x6c, 0xb9, 0xdc, 0x80, 0x9b, 0xb9, 0xcb, 0xfc, 0xe5, 0x36,
	0xba, 0x41, 0xe5, 0x73, 0x9b, 0xd8, 0x93, 0x4f, 0x9b, 0x3c, 0xe0, 0xc3, 0x40, 0xc8, 0xc0, 0xb7,
	0xfc, 0x1b, 0xe9, 0x68, 0xf8, 0x8f, 0xfa, 0x58, 0xb3, 0xb3, 0x8f, 0xcf, 0xaf, 0x7d, 0x74, 0x4c,
	0x7a, 0xc5, 0x76, 0x52, 0x84, 0x15, 0xbe, 0x1c, 0xb8, 0xbd, 0x4c, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x8a, 0x0d, 0xec, 0x0c, 0xd4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleServiceClient interface {
	Example(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error)
}

type exampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleServiceClient(cc grpc.ClientConnInterface) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) Example(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error) {
	out := new(ExampleResponse)
	err := c.cc.Invoke(ctx, "/main.ExampleService/Example", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceServer is the server API for ExampleService service.
type ExampleServiceServer interface {
	Example(context.Context, *ExampleRequest) (*ExampleResponse, error)
}

// UnimplementedExampleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExampleServiceServer struct {
}

func (*UnimplementedExampleServiceServer) Example(ctx context.Context, req *ExampleRequest) (*ExampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Example not implemented")
}

func RegisterExampleServiceServer(s *grpc.Server, srv ExampleServiceServer) {
	s.RegisterService(&_ExampleService_serviceDesc, srv)
}

func _ExampleService_Example_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).Example(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ExampleService/Example",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).Example(ctx, req.(*ExampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Example",
			Handler:    _ExampleService_Example_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example-service.proto",
}
